# This file was generated by GoReleaser. DO NOT EDIT.
cask "mediaconv" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "6a6291395698dea3660eeff9999d139b6dfebc0ac4e186e8f6bca0e41d2c7703"
      url "https://github.com/Amad3eu/mediaconv/releases/download/v#{version}/mediaconv_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "21d9d736af84eaec7da87cf7b33c83926d8cfc155d02f20ea707b1856dc88f78"
      url "https://github.com/Amad3eu/mediaconv/releases/download/v#{version}/mediaconv_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c3ce1f5f9cce212e9065d383014a6f362ab241bf21da3923fd307d32419cc4ff"
      url "https://github.com/Amad3eu/mediaconv/releases/download/v#{version}/mediaconv_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "476c0a1f089c720e2cb2f0a3fa458e2a9b082442b61f7c87b0137fee435aef5c"
      url "https://github.com/Amad3eu/mediaconv/releases/download/v#{version}/mediaconv_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mediaconv"
  desc "Safe command-line media converter powered by FFmpeg."
  homepage "https://amad3eu.github.io/mediaconv/"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "mediaconv"

  # No zap stanza required
end
