# This file was generated by GoReleaser. DO NOT EDIT.
cask "mediaconv" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "f78612c0542856d6fa13cdf8e61c7ea1d6e91dee77704ef37541d78550ba4f75"
      url "https://github.com/Amad3eu/mediaconv/releases/download/v#{version}/mediaconv_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b87b84ac801e8c76f4fbe004d2495c6743b3930b26fa69a3e85c4c5fcefbd6ec"
      url "https://github.com/Amad3eu/mediaconv/releases/download/v#{version}/mediaconv_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "795a7f195be52b268554db5f82fc887f1e236aaf5d5802c6ec74895ec17fcad2"
      url "https://github.com/Amad3eu/mediaconv/releases/download/v#{version}/mediaconv_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2000c7fec48f253bd2999613a22940c3e21c973bb628bd69e2b060a0f65865c4"
      url "https://github.com/Amad3eu/mediaconv/releases/download/v#{version}/mediaconv_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mediaconv"
  desc "Safe command-line media converter powered by FFmpeg."
  homepage "https://amad3eu.github.io/mediaconv/"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "mediaconv"

  # No zap stanza required
end
