# This file was generated by GoReleaser. DO NOT EDIT.
cask "mediaconv" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "a9f606c80d3200e31965ffaf5c750a360aadd7db558b2134db300263de3f9aa9"
      url "https://github.com/Amad3eu/mediaconv/releases/download/v#{version}/mediaconv_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f9c57336bc4ecf03807cfe804862bf163135c55091b763d955c9180ab8d97137"
      url "https://github.com/Amad3eu/mediaconv/releases/download/v#{version}/mediaconv_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4e62662fab1ea5528ba8e866c02fa97707d6c01c864b0a903a275baf7348b227"
      url "https://github.com/Amad3eu/mediaconv/releases/download/v#{version}/mediaconv_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "01c7e3a270422f870ef3214ed2af7ba7d04e8e4238a55636d5069510b3b0b3ab"
      url "https://github.com/Amad3eu/mediaconv/releases/download/v#{version}/mediaconv_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mediaconv"
  desc "Safe command-line media converter powered by FFmpeg."
  homepage "https://amad3eu.github.io/mediaconv/"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "mediaconv"

  # No zap stanza required
end
